### ISSUE TITLE
New Relic functional example

### ISSUE THREAD

**Issue by gregnetau** [opentelemetry-php/otel-roadrunner-example#2]
Hello and thanks for the otel + roadrunner example.

We have tried to use this code with our otel exporter for newrelic, and we are able to the gzip+http middlewear "blobs" but no other spans in our application.

Have you had any experience with instrumenting an existing laravel app with otel, and or advice here as to where the we could be going wrong with no laravel middlewear spans making their way via otel?

**Comment by brettmc** [comment]
Hi @gregnetau 
This example needs updating, as our otel implementation has improved. If you have added some manual instrumentation to your application and are not seeing spans exported, then it's usually a configuration issue.
There are a couple of ways to instrument a Laravel application. I've just released a new version of https://packagist.org/packages/open-telemetry/opentelemetry-auto-laravel which will auto-instrument a Laravel app.

You'll find help over in our slack channel: https://cloud-native.slack.com/archives/C01NFPCV44V

I'll update this example too, I have been using otel-php + roadrunner extensively.

**Comment by brettmc** [comment]
I've updated the example to work with our current (release candidate) version of the SDK.
![Screenshot from 2023-09-21 09-15-03](https://github.com/opentelemetry-php/otel-roadrunner-example/assets/4978962/722efe37-c256-467f-bd89-5cbbfc5e3240)

**Comment by bobstrecansky** [comment]
Closing this.  We are trying to consolidate all of our issues in https://github.com/open-telemetry/opentelemetry-php/issues - please feel free to reopen there if you're still having trouble.
